### ISSUE TITLE
Missing subtitle offset option

### ISSUE THREAD

**Issue by luispabon** [jurialmunkey/skin.eminence.2#10]
When on playback, the only two options for subtitle are either the language, or download. Subtitle offset is missing here.

**Comment by wmariz** [comment]
Add some Video OSD Shortcuts #18

**Comment by jurialmunkey** [comment]
Thnx to @wmariz this is now fixed. :)

**Comment by markelhas** [comment]
@jurialmunkey I've just installed the skin on kodi 17, and when I try to get subtitle offset the only 2 options are Download and Enable <LANG> options.
Any special configuration needed to have the offset glider on screen?

**Comment by luispabon** [comment]
@markelhas the option is there, but in the wrong place. It's in the audio options screen.

**Comment by markelhas** [comment]
@luispabon yap it's there, but from there u can see the video and subtitles in order to sync it ... useless !!!
And since I can't use the short key ctrl+t, don't have the ctrl on my minix command,,I'm not able to sync the subtitles ...
