### ISSUE TITLE
Power Button not working properly

### ISSUE THREAD

**Issue by christoophat** [jurialmunkey/skin.eminence.2#100]
When trying to shut down Kodi while using Eminence, the Exit option produces "Failed to Play Game (the required files can't be found)" popup on screen.
I have to switch to another skin to be able to power down Kodi. (Kodi 19.2, latest Eminence v from repo)

**Comment by drinfernoo** [comment]
In the forum, he said he was having issues with "Power Off" 🤔

**Comment by jurialmunkey** [comment]
Xbmc prefix was removed in Matrix (its just `quit()` now not `xbmc.quit()`). You probably had an old skinshortcuts configuration or it was carried over from another skin (skinshortcuts is shared across skins).
