### ISSUE TITLE
Music files unable to display tag info onscreen

### ISSUE THREAD

**Issue by christoophat** [jurialmunkey/skin.eminence.2#102]
I have 4.1.2 installed, and media tag checked in settings. This info is important to me, as I use Kodi for my ever expanding music collection. When I first updated this skin, as per Jurial's comment bitrate/sample rate info could be seen on the main screen when song was playing. Not it only is listing the song title and elapsed time/song length. I am hoping to be able to have the album coverart, osd controls and the media tags all listed onscreen as music plays a la Amber. Is that doable/possible

![Amber media tags](https://user-images.githubusercontent.com/24498265/137955386-3152e357-9770-40a5-91fa-ff9cdceb78bf.jpg)

**Comment by christoophat** [comment]
OK, from Home Screen I press Music, then right arrow, and select Party Mode. It fills the glasses, then I get the first 10 tracks showing as a "Playlist", and the first track is playing. Below this Playlist are all the audio track info tags - perfect!
![Screen 01](https://user-images.githubusercontent.com/24498265/138014312-4e4411de-a853-4e1a-a4a5-d3f3a8044d42.jpg)

**Comment by christoophat** [comment]
But...once I back button out of this view, those tags are never seen again, only track name/track time/time remaining.
![screen 03](https://user-images.githubusercontent.com/24498265/138014517-886dfebb-230d-4398-b8ad-49bee3a571ae.jpg)

**Comment by christoophat** [comment]
It would be so cool if those complete media flags/tags could be seen in this view. Thank you for your time.
![Screen 02](https://user-images.githubusercontent.com/24498265/138014610-0ce60ab9-c451-4031-8312-851dabc29c5d.jpg)
.

**Comment by christoophat** [comment]
Hi, I tried to d/l from your repo, but I only see 4.1.14 listed?. The link above am unsure what to do

**Comment by derrgoo** [comment]
Need to visit git hub branch and download new version.
