### ISSUE TITLE
Static background gets overridden with fanart

### ISSUE THREAD

**Issue by mvn23** [jurialmunkey/skin.eminence.2#107]
After upgrading to the Matrix version of this skin, I noticed that my background changes from time to time.

I'm trying to create a minimalist setup with only the home menu and sub menus, without any further widgets or other distracting elements. To achieve this, I have applied the following settings:
* `Home > Show widget information`: off
* `Home > Show widget posters`: Never
* `Home > Show widget discart`: off
* In `Home > Customise home menu`, all items have `Widget` set to `None` and `Background` set to the same static image.
* `Background > Show fanart`: off
* `Background > Background overlay image`: set to static image (same as for `Customise home menu` items)
* `Background > Fanart fallback image`: None

Despite this, every once in a while my background gets temporarily overridden with a fanart image. When I press `up` on my remote, I see a `Spotlight` widget showing the same movie from which the fanart seems to originate.

As a workaround, I have removed the entire `<!-- Home Widget -->` section from here:
https://github.com/jurialmunkey/skin.eminence.2/blob/c4b26fe747e8481fdee7ce96c9efce6e7e62d39d/16x9/Includes_Home.xml#L508-L728
This removes the `Spotlight` widget and fixes the background changes, but of course it's not a proper fix for the underlying issue.

Arch Linux x86_64
Kodi 19.3
skin.eminence.2 v4.1.19

**Comment by jurialmunkey** [comment]
You need to set the fallback widget.

- Create a folder with a single image
- Go to Pictures and add the folder as a source (you might need to add the Pictures menu item temporarily if you've removed it)
- Go to Skin Settings > Home > Fallback Widget > Pictures Sources > Your Folder

Now the fallback widget will be your image.

**Comment by jurialmunkey** [comment]
Latest version also makes it a bit easier by adding a "Replace fallback widget with image" option which saves you needing to add it as a picture source.

**Comment by mvn23** [comment]
Adding the fallback widget works indeed. Thank you!
