### ISSUE TITLE
Media Flags/Info mis reported for UHD/2160P videos - shown as SD

### ISSUE THREAD

**Issue by joekellyco** [jurialmunkey/skin.eminence.2#110]
The Repo release doesn't have this issue, but using 4.17+ ( i didnt try below) shows all UHD videos in my movie library as SD/480P for the media flags.   1080P reports correctly and 720 does, but 2160P is broken.   the repo version of 4.10 works fine for reporting the media flags.    This is on a fresh update/install of Kodi 19.3 / on OSMC.

**Comment by jurialmunkey** [comment]
I can't reproduce. On 4.1.21 my 4k movies are correctly showing the HD 2160p flag.

Check that the correct resolution is showing in Estuary. If it's incorrect there too then it's not a skin issue.

**Comment by joekellyco** [comment]
Just checked in 2 other skins (Estuary and OSMC), and 4.1.0 of Eminence 2 (from the repo)  and all show correct. 

Eminence 2  4.1.17, and 4.1.20b show the media flag  as SD/480 with the icons in the movie info view and just browsing (only for movies at 2160P though, 1080, 720 all show correctly).  ( I didn't try more versions of Eminence, but those two show the wrong ones.  I can switch between them and replicated it every time.

**Comment by jurialmunkey** [comment]
Can you get me a screenshot of estuary with the correct tag showing. I'm interested to know what it's reporting as. If Eminence is falling back to the SD icon then that means there's no icon matching that resolution but there's already icons for 2160 and 4k so your files must be reporting something different.

**Comment by joekellyco** [comment]
thanks yeah I'll give it a try!   Thanks for looking into it!

**Comment by joekellyco** [comment]
Yup that worked, thanks!
