### ISSUE TITLE
Gui Missing items

### ISSUE THREAD

**Issue by kovacicjanez** [jurialmunkey/skin.eminence.2#121]
Hi,

in Kodi nexus Power menu items missing.
Problem in DialogButtonMenu.xml
Log: error <general>: Control 9000 in window 10111 has been asked to focus, but it can't

also missijng items in some addons:

info <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2023-07-07 09:06:05.282 T:47820 warning <general>: Skin has invalid include:

**Comment by jurialmunkey** [comment]
Skin already has this control in this window
https://github.com/jurialmunkey/skin.eminence.2/blob/ed21671f2f0d3e93e6a2aae9287ef889ac715a15/16x9/DialogButtonMenu.xml#L25-L29

You can setup the power menu in the skin settings.

**Comment by kovacicjanez** [comment]
Hi,

I reset Power menu to default and now works.

Do you have any idea why only on specific addon don't show content when i go to Movies or TV shows section?
info : Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2023-07-07 09:06:05.282 T:47820 warning : Skin has invalid include:

![image](https://github.com/jurialmunkey/skin.eminence.2/assets/55586975/079f4874-03db-41e0-a63e-d62284a29bda)
