### ISSUE TITLE
Menu fix

### ISSUE THREAD

**Issue by kovacicjanez** [jurialmunkey/skin.eminence.2#122]
Hi,

Do you have any idea why only on specific addon don't show content when i go to Movies or TV shows section?
info : Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2023-07-07 09:06:05.282 T:47820 warning : Skin has invalid include:

Addon is plugin.video.elementum.

Also same issue in artic horizon 2.

**Comment by jurialmunkey** [comment]
Can't help with banned addons.

Probably the addon sets a weird content type or you've setup the wrong content type on a widget.
