### ISSUE TITLE
Top left icon disappears

### ISSUE THREAD

**Issue by Flavien** [jurialmunkey/skin.eminence.2#13]
When adding a tile on the home screen to open a video add-on such as Exodus or YouTube, and then opening that tile, the top left icon disappears.

![missingicon](https://cloud.githubusercontent.com/assets/296540/20775284/1303355e-b752-11e6-9b02-2f15e4811ea4.jpg)

I am using Eminence 2.5.8 on Kodi Krypton beta 5.

**Comment by Flavien** [comment]
@jurialmunkey Any idea when/if that will be fixed?

**Comment by jurialmunkey** [comment]
@Flavien 
Sorry haven't been able to reproduce this bug until recently so haven't been able to fix it. I think its related to a visibility condition with dialogbusy not working correctly. Figured out a work around that hopefully should fix this (fixes on my end as far as I can tell). Can you test latest git and see if the issue persists?

**Comment by Flavien** [comment]
Yes, I tested the master branch and it's fixed. Well done!

**Comment by Flavien** [comment]
Will you be pushing an update to the Kodi official repository?

**Comment by jurialmunkey** [comment]
@Flavien Yes I will be. I'm just waiting for the new version of skin.helper to be accepted into the repo as the latest version of the skin depends on the new skin helper
