### ISSUE TITLE
Media Flags on OSC

### ISSUE THREAD

**Issue by soofuzz** [jurialmunkey/skin.eminence.2#16]
Hey,

I was wondering if there was a way to get the media flags to show on Video Playback for both live tv and media library. Ive shown an example in image one on another skin and what it looks like on eminence 2.

![screen shot 2016-11-20 at 8 59 22 pm 2](https://cloud.githubusercontent.com/assets/11738103/20465384/a3c71bd2-af64-11e6-8588-f2f8ac6a17b6.png)
![screen shot 2016-11-20 at 8 58 47 pm 2](https://cloud.githubusercontent.com/assets/11738103/20465385/a819bce4-af64-11e6-8aba-a550337a93e3.png)

maybe theres a way to fit it next to the title in tiny image formats or under it purple text. Thanks.

**Comment by jurialmunkey** [comment]
Press UP from OSD controls will give more info about current file.
