### ISSUE TITLE
Search windows not displayed

### ISSUE THREAD

**Issue by duboisst** [jurialmunkey/skin.eminence.2#27]
The search windows (in film library) is not opened when I clik on search. Click on search has no effect.
Each time I press Search, the following lines are added in kodi.log
`21:13:02 T:140058611677248 WARNING: Skin has invalid include: Dimensions_Fullscreen`
`21:13:06 T:140056115271424 WARNING: Previous line repeats 2 times.`
`21:13:06 T:140056115271424   ERROR: GetDirectory - Error getting /storage/.kodi/userdata/profiles/Famille/library/video`
`21:13:07 T:140056115271424   ERROR: GetDirectory - Error getting /storage/.kodi/userdata/profiles/Famille/library/music`
`21:13:07 T:140058611677248   ERROR: Control 3 in window 13000 has been asked to focus, but it can't`

My system is OpenElec 7

**Comment by jurialmunkey** [comment]
Sorry the Jarvis version of the skin is no longer being maintained. Development has moved onto Krypton.
