### ISSUE TITLE
Movie and TV Hubs

### ISSUE THREAD

**Issue by vwchu** [jurialmunkey/skin.eminence.2#35]
I use Arctic Zephyr and this theme interchangeability. I was wondering if support for the Movie Hub (1111) and TV Hub (1112) could be to this theme in-line with Arctic Zephyr.

**Comment by jurialmunkey** [comment]
Latest changes on github for Eminence and Arctic Zephyr should make the hubs compatible with each other (make sure you have latest version of both).
