### ISSUE TITLE
No visual indication for manual skipping

### ISSUE THREAD

**Issue by aphirst** [jurialmunkey/skin.eminence.2#40]
A Kodi feature we use regularly is skipping to a specific timestamp, i.e. where one types the timestamp then presses Enter.

This feature still works fine with this Skin, of course, but unlike with other skins we don't seem to get any visual indication until we press Enter, i.e. there is no on-screen dialog of what we've typed before we actually attempt the Skip.

Is this an oversight, or is there something I've misunderstood? I've tried to read through the Skin settings but don't see anything relevant.

LibreELEC 8.0.2
Kodi 17.3
rPi 3

If you need any more information, please don't hesitate to ask.

**Comment by mgonzales71** [comment]
FYI - this changed in Krypton and above for skins.
need to update VideoFullScreen.xml 

here is the simple code I used in skin Titan:
```

	<!-- Jump to Time Code Overlay -->
		<control type="group" id="1">
			<visible>!String.IsEmpty(Player.SeekNumeric) + !Window.IsVisible(VideoOSD)</visible>
			<animation type="Visible" condition="!Window.IsVisible(SeekBar)">
				<effect type="zoom" start="90" end="100" center="auto" tween="back" easing="out" time="200"/>
				<effect type="fade" start="0" end="100" time="200"/>
			</animation>
			<control type="image" id="1">
				<left>75</left>
				<top>300</top>
				<width>140</width>
				<height>50</height>
				<texture border="5">diffuse/panel.png</texture>
				<colordiffuse>$INFO[Skin.String(OSDPanelColor)]</colordiffuse>
			</control>
			<control type="label" id="1">
				<left>75</left>
				<top>300</top>
				<width>140</width>
				<height>50</height>
				<label>$INFO[Player.SeekNumeric(hh:mm:ss)]</label>
				<font>Bold30</font>
                <textcolor>$INFO[Skin.String(OSDPrimaryTextColor)]</textcolor>
                <shadowcolor>$INFO[Skin.String(OSDPrimaryTextShadowColor)]</shadowcolor>
				<aligny>center</aligny>
				<align>center</align>
			</control>
			<control type="label" id="1">
				<left>75</left>
				<top>350</top>
				<width>500</width>
				<height>50</height>
				<label>$LOCALIZE[31806]</label>
				<font>Bold26</font>
				<textcolor>white</textcolor>
				<shadowcolor>black</shadowcolor>
				<aligny>center</aligny>
				<align>Left</align>
			</control>
		</control>
```

The following basic code should work for any skin (it is not localized, hard coded white text and a fallback Arial font) but get you basic functionality for this or any skin missing this new method,

Best of luck - just happen to be passing by and saw this so shot you a quick answer until this skins dev can get time to customize it for the skin.

```

	<!-- Jump to Time Code Overlay -->
		<control type="group" id="1">
			<visible>!String.IsEmpty(Player.SeekNumeric) + !Window.IsVisible(VideoOSD)</visible>
			<animation type="Visible" condition="!Window.IsVisible(SeekBar)">
				<effect type="zoom" start="90" end="100" center="auto" tween="back" easing="out" time="200"/>
				<effect type="fade" start="0" end="100" time="200"/>
			</animation>

			<control type="label" id="1">
				<left>75</left>
				<top>300</top>
				<width>600</width>
				<height>30</height>
				<label>$INFO[Player.SeekNumeric(hh:mm:ss)]</label>
				<font>font13</font>
                <textcolor>white</textcolor>
                <shadowcolor>black</shadowcolor>
				<aligny>center</aligny>
				<align>center</align>
			</control>
			
			<control type="label" id="1">
				<left>75</left>
				<top>330</top>
				<width>600</width>
				<height>30</height>
				<label>Jump to Specific Time (hh:mm:ss)</label>
				<font>font13</font>
				<textcolor>white</textcolor>
				<shadowcolor>black</shadowcolor>
				<aligny>center</aligny>
				<align>center</align>
			</control>
		</control>
```

## a screenshot of basic code in action

![kodi_2017-09-19_19-45-10](https://user-images.githubusercontent.com/6510026/30624703-d19987c2-9d73-11e7-8e56-0be2d734742b.png)

**Comment by jurialmunkey** [comment]
Sorry, I've been very busy lately. I will try to make an update with this change soon.

**Comment by Dwosky** [comment]
Any update over this issue? I think it would be a great improvement, since many of us use this skip feature.

**Comment by FlashyDuck** [comment]
@jurialmunkey Is this still something you are working on? It's the only thing I'm missing in this skin.

@mgonzales71 In which file have you implemented this? I tried to add this code to VideoFullScreen.xml but that breaks the skin. Any ideas?
