### ISSUE TITLE
Menu Hub

### ISSUE THREAD

**Issue by D4rkPh0en1x** [jurialmunkey/skin.eminence.2#44]
Hi
Is there a documentation on how to customize the hubs in the mainmenu?
I see that hub id 1101 and 1102 is used but I need to use some more with other categories/nodes.

Many thanks in advance - Sorry I don’t know where to write else...

**Comment by jurialmunkey** [comment]
Please use the forums for support
https://forum.kodi.tv/showthread.php?tid=237538
