### ISSUE TITLE
Settings in Movie OSD missing

### ISSUE THREAD

**Issue by Siggi0904** [jurialmunkey/skin.eminence.2#47]
Hi,

I'm looking for the settings button in the movie OSD. Is it missed in these skin?
In standard skin it is in, here you can setup some additional sound and video options.

Hope you can add it or gimme an updated file to add these button.

Great thanks.

**Comment by Siggi0904** [comment]
These settings I mean: https://kodi.wiki/view/Video_playback#Settings

**Comment by jurialmunkey** [comment]
Click the button on the osd that says "Audio" or "Video" to access these settings.

**Comment by Siggi0904** [comment]
there is no button in this skin

**Comment by jurialmunkey** [comment]
Um, yes there is!

https://i.imgur.com/xMHpWul.png
