### ISSUE TITLE
Not compatible with leia RC5

### ISSUE THREAD

**Issue by PaulFinch** [jurialmunkey/skin.eminence.2#53]
Eminence is the best theme ever. The leia branch worked well in RC4. However it is automaticaly disabled (as marked as not compatible) in RC5

**Comment by dasmaetthes** [comment]
Change in addon.xml  

`<import addon="xbmc.gui" version="5.13.0"/>`

 to

`<import addon="xbmc.gui" version="5.14.0"/>`

**Comment by PaulFinch** [comment]
Fixed in 3.0.1
