### ISSUE TITLE
Vertical scroll bar

### ISSUE THREAD

**Issue by Windex961** [jurialmunkey/skin.eminence.2#54]
When you enable standard scroll bars (the vertical ones on the left side) they only go about half way through a list before stopping (usually around "N" or "O"). Seems to be the issue in the library as well as streaming sources.

**Comment by jurialmunkey** [comment]
Yep, can reproduce. Not quite sure why it's happening. I'll look into it and try to find a fix.

**Comment by jurialmunkey** [comment]
I think I've fixed the issue. Please test latest git and confirm.

**Comment by Windex961** [comment]
Just installed the zip, still seeing the same issue
