### ISSUE TITLE
Small fonts and icons using iagl on Kodi 18

### ISSUE THREAD

**Issue by robmcc1983** [jurialmunkey/skin.eminence.2#55]
Hi,
Love your skin been using for a while now but have found a small issue.
When I use iagl, the screen where you select launch, trailer download etc.
The icons in the box are very small and so is the font.
Thanks
Rob

**Comment by jurialmunkey** [comment]
Screenshot? Looks fine to me.

**Comment by robmcc1983** [comment]
This is a screen shot from IAGL using your skin.

![screenshot_20190226-235259](https://user-images.githubusercontent.com/19917296/53455322-f62d3380-3a21-11e9-9d56-d69f590e1330.jpg)

And this below is a screenshot of IAGL using Kodi default skin.

![screenshot_20190226-235355](https://user-images.githubusercontent.com/19917296/53455357-15c45c00-3a22-11e9-9ebe-5bd70fa93b0a.jpg)

As you can see the 4 icons towards the bottom right are alot smaller using you skin.
Theses screen shots were taken on my phone so you can see the difference.
It's more noticeable on my TV using my raspberry pi as obviously the TV is a bigger screen.
Thanks

**Comment by jurialmunkey** [comment]
Ah okay, I see what you are saying - it's likely due to some difference between defaults. Not much I can do about it without making a custom skin for IAGL info (which is on the books, as I recently started using it myself and I would like to get an integrated look). No ETA, but hopefully sometime in the next few weeks.

**Comment by robmcc1983** [comment]
I have got around this for the time being by making IAGL download and launch game when selecting rom rather than showing info first :) you can still see the info by highlighting the game and pressing the info button :)
Thanks
