### ISSUE TITLE
Skin does not select the proper posters with TV series

### ISSUE THREAD

**Issue by JeroenTuinstra** [jurialmunkey/skin.eminence.2#57]
Fresh install of kodi 18.1. Fresh install from Kodi repository Eminence 3.0.4. 
Going to TV Shows and changing the view to anything with "icons" in them and it shows not the posters of each season, but the same poster for all seasons. Only in view "showcase" are the different posters visible. 
This for now seems to be the only (but for me a major flaw, makes me consider other skins) with this version of Eminence.
![error-1](https://user-images.githubusercontent.com/47460053/53306251-0fe84280-388b-11e9-93cb-044283c7ce8b.jpg)
![error2](https://user-images.githubusercontent.com/47460053/53306254-72414300-388b-11e9-99d1-a3107fb3fa02.jpg)
![showcase](https://user-images.githubusercontent.com/47460053/53306256-15de2380-388b-11e9-88a0-dfbd78878b3d.jpg)

Bug report: https://www.dropbox.com/s/j0va4ref4c5pw5d/kodi-problem%20eminece.log?dl=0

**Comment by jurialmunkey** [comment]
Can you test the latest git version? Should be fixed now.

**Comment by JeroenTuinstra** [comment]
Thank you! It got fixed. Much appreciation for all the work!

**Comment by jurialmunkey** [comment]
Excellent. Thanks for the confirmation.

**Comment by KingSalehZar** [comment]
Sorry where and how can I get the git version because I have the same problem. I'm new to this.
