### ISSUE TITLE
PVR artwork no longer shows in Kodi 18

### ISSUE THREAD

**Issue by robmcc1983** [jurialmunkey/skin.eminence.2#60]
With your skin on Kodi 17 I always used to get a screenshot of artwork on my TV channels using PVR within kodi. 
On Kodi 18 it appears it no longer work.

Below is a screenshot from how it use to look on Kodi 17.
On Kodi 18 I just get a box with the Kodi logo in it.
Thanks

![Screenshot_20190309-000929](https://user-images.githubusercontent.com/19917296/54107142-30a6b100-43d0-11e9-8194-c3d4ab2ad8a7.jpg)

**Comment by jurialmunkey** [comment]
Did you install skin helper?
I don't use PVR so I can't test, but nothing should have changed.

**Comment by robmcc1983** [comment]
Hi,
Yes I have skin helper installed.
Although since posting this issue I have tried a couple of other skins and they to also do not work.
So I tried Kodi 17.6 and all the skins that don't work with PVR artwork in Kodi 18 (including yours) all work fine.
So it appears something has changed within Kodi itself from version 17 to 18.
Thanks

**Comment by jurialmunkey** [comment]
Check script.module.metadatautils settings.

**Comment by robmcc1983** [comment]
How would I check settings for this, I can't seem to find it anywhere in Kodi.

Thanks

**Comment by jurialmunkey** [comment]
System Settings > Add-ons > Manage Dependencies > Metadata and Artwork Module.
