### ISSUE TITLE
Missing/blank context menu item

### ISSUE THREAD

**Issue by jamieburchell** [jurialmunkey/skin.eminence.2#63]
Version 3.0.4 on Kodi 18.

In Add-ons > install from repo > Look and feel > [context menu] there is a blank item with checkbox second from bottom.

**Comment by jurialmunkey** [comment]
I don't have this blank item. Probably some context menu addon that you have installed.

**Comment by jurialmunkey** [comment]
Oh you mean the view menu, not context.

**Comment by jurialmunkey** [comment]
Fixed in this commit: https://github.com/jurialmunkey/skin.eminence.2/commit/e5384fb1a4454d48a757e1864363f84fe7495778
