### ISSUE TITLE
Feature request : 3D token on movies

### ISSUE THREAD

**Issue by poofyteddy** [jurialmunkey/skin.eminence.2#65]
Hello,
First thank's for the great work,  i have been using your skin for years, and all my family find it simple and beautiful.
There is one thing missing for me tho, i have lot of movie how have both a 4h file, and a 3d file. sadly your skin show no token on the movie poster indicating that it is a 3d movie.
I usually have to try both to find the right one (because it is NEVER the first one i try obviously :smile: ) and i saw that other skin did it.
I know 3d is not very used, and that you work on your newer skin, so i"m not really expecting it, but if you could add that i would be very grateful :)

have a nice day

**Comment by jurialmunkey** [comment]
Yes it does show 3d icon.

Make sure you have Media Flags enabled in Skin Settings.

`Skin Settings > Library > Show media flags`
