### ISSUE TITLE
Color Picker / Customize home menu not working

### ISSUE THREAD

**Issue by hawkeyexp** [jurialmunkey/skin.eminence.2#67]
Hi,

working with kodi 18.5 (rpi and win) the color picker is shown and you can select and save a color but it seems it is not wirtten to settings and is not used on home screen :-(

Custom colors from colors menu in skin settings is enabled and all deps are installed.

**Comment by jurialmunkey** [comment]
Works fine for me on 18.5 on Windows and LibreELEC.

Check that you have `script.skin.helper.colorpicker` installed and enabled.

I tested with these versions:
v1.0.13 of colorpicker.
v1.1.24 of skinhelper.

**Comment by hawkeyexp** [comment]
Hi, i checked all again on windows and on a rpi3 system but all deps are present and the effect is still same - for testing i changed the button 9701 in script-skinshortcuts.xml from shortcutproperty to skinstring and this is written to settings.xml so the base function is working... any ideas? I cant't understand why it is working for you and not for me in two different systems...
