### ISSUE TITLE
Restore of skin backups

### ISSUE THREAD

**Issue by hawkeyexp** [jurialmunkey/skin.eminence.2#68]
Hi,

working with kodi 18.5 (rpi and win) the skin backup is working and a backup file are written correctly.
If you try to restore from skin settings menu it doesn't work fully. The progress is very fast and not all is restored.
If the skin helper service skin backup is manually launched from addons and same file is restored it needs more time and is restoring all correctly.

**Comment by jurialmunkey** [comment]
This commit should hopefully fix the issue: https://github.com/jurialmunkey/skin.eminence.2/commit/1e71ace6fcae738df4f0fc241ec21357e2cece1b

However, Skin Helper addons are no longer maintained, so if this doesn't work then it is unlikely I am able to fix this issue.
