### ISSUE TITLE
incompatibility with artist slideshow's last update

### ISSUE THREAD

**Issue by chewiiie** [jurialmunkey/skin.eminence.2#69]
there is now a warning instead of the pictures in the slideshow while playing music, claming that the skin needs to be updated to support the new slideshow display method.

**Comment by petwri** [comment]
Backing this, I have the same issue. Will this be fixed?

**Comment by jurialmunkey** [comment]
Should be fixed with this commit: https://github.com/jurialmunkey/skin.eminence.2/commit/36370f3b85d0b61e9100c0fbf0e4548f3a690494

**Comment by chewiiie** [comment]
works perfectly! thanks
