### ISSUE TITLE
Individual tile color customization not working

### ISSUE THREAD

**Issue by vitadome** [jurialmunkey/skin.eminence.2#70]
Hello, I'm trying to setup individual tile colors within eminence skin but it's not saving my color selection.

**I first turn on the setting:**
Skin Settings > Colors >Enable individual tile colors in home customisation = check mark

**Then I try to set the color setting:**
Skin Settings > Home > Customise home menu
Color > Select color > Save

It doesn't appear the "save" is making the change in the skin.

I'm using Windows 10, Kodi 18.5 and confirmed I'm using correct skin helper versions you mentioned in a previously closed issue.

**Comment by jurialmunkey** [comment]
Fixed in Matrix version.

**Comment by udvzso** [comment]
That's exactly my problem. I use Eminence Mod 2 on Kodi Matrix 19.2 on AndroidTV.

**Comment by jurialmunkey** [comment]
I don't make the mod - I only make the official version of the skin.

**Comment by udvzso** [comment]
Oh, I'm sorry, I overlooked ...
