### ISSUE TITLE
CJK Font Support

### ISSUE THREAD

**Issue by Momochi-Kiruya** [jurialmunkey/skin.eminence.2#77]
I'm using this skin, but it isn't support arial font to view CJK Font.
So, I made CJK Completability Font. Can you support additional Font?

Based on NanumBarunGothic, and English font is Roboto. Also, Japanese and Chinese Font are imported by Noto Sans CJK.

**Comment by jurialmunkey** [comment]
Arial support added in v4.0.9 for Matrix
https://github.com/jurialmunkey/skin.eminence.2/releases/tag/v4.0.9
