### ISSUE TITLE
Commits missing  from Isengard merge into master

### ISSUE THREAD

**Issue by guidosarducci** [jurialmunkey/skin.eminence.2#8]
Hi jurialmunkey,
I noticed the following fixes committed to the Isengard branch never made it into master during the last few merges. Could you review and handle manually, or let me know if I should PR again?

3cccf71fc94f7f499bd2002ce1aa99924b465cc5
583a817c9e6af541dfa84ed2ac73211342d8c84a

Thanks and take care...

**Comment by jurialmunkey** [comment]
Not sure why those didn't get merged, I thought I did merge them. Oh well, readded. Thanks for the headsup!

**Comment by guidosarducci** [comment]
No problem, and thanks for updating.  I'm really glad to see an official repo release coming up too!  BTW, I know you had it on your ToDo list, but do you plan to enable "current video playlist" for the release?  It's one of those Kodi basics, and came up on the forum ages ago, but I think life got busy afterwards :^)

Great work as always...
