### ISSUE TITLE
[Request] PVR Guide group control

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/skin.eminence.2#83]
Like artic horizon can I request categories to be added to eminence PVR TV Guide on the top? Picture for reference. 

![image](https://user-images.githubusercontent.com/63697905/135221431-fbacaee0-1b5d-4236-a27d-22845dd11364.png)

**Comment by jurialmunkey** [comment]
Yep just haven't got to looking at epg stuff yet but will soon!

**Comment by derrgoo** [comment]
Great thanks. Looking forward to it. 👍

**Comment by derrgoo** [comment]
It seems after update 4.1.13 the group selector in PVR was deleted. Al new updates it doesn't appear.

**Comment by derrgoo** [comment]
> > Good news. Updated from repo and showing up. 👍 maybe I messed something up last time downloading from github. Anyway all good. Thanks.
> 
> 
> 
> If you download from github you need to give the zip a unique name otherwise kodi thinks it's an old version and uses the zip it has cached with the same name.
> 
> 
> 
> That's why you should download the zips from the releases section rather than the code button. The releases are all uniquely named

Okay, that makes sense. I never knew that before. 👍
