### ISSUE TITLE
[Bug] Weather widget opens fanart not weather window

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/skin.eminence.2#84]
As per title. 
When clicking the weather widget it should take the user to weather window (not the slideshow).
See: https://github.com/jurialmunkey/skin.eminence.2/issues/82#issuecomment-927315245

**Comment by derrgoo** [comment]
Mine takes me to weather window.

**Comment by jurialmunkey** [comment]
> Mine takes me to weather window.

When you press up to select the weather widget and press Select? Because that should open the fanart fullscreen currently. Note this is specifically the weather _widget_ not a weather _shortcut_ on a home tile or submenu.
