### ISSUE TITLE
[Request] Lock 🔒 View button for Media Views

### ISSUE THREAD

**Issue by Nuklear92** [jurialmunkey/skin.eminence.2#85]
As the title says, an option to lock any media view of your choosing for different categories like, Season, Episodes, Movies and TV Shows. 

Example, as of now if I select a different media view from the default one in Episodes. That media view will only be present for that list page only as soon as you click on "Next Page" or "Next" then the next page on will be shown with the Default media view not with the one you selected. Same for Movies, TV Shows, when you select a different media view that media view will only stick to that list page you're currently viewing. Being, page 1,2, etc. if you hit back/return media view is back to default and never sticks skin wide or categories e.g (TV Shows lists (Poster list), Seasons list (Media Info), Episodes lists (List info), Movies lists (Medium Poster) etc.

**Comment by jurialmunkey** [comment]
You can already Lock Views. Choose "Lock View" from the top right of the view selection screen...

![Honeyview_Honeyview_screenshot00062 (2)](https://user-images.githubusercontent.com/4618719/135737127-b5304b7f-5bb3-42e0-8704-ed7d6b467649.jpg)

**Comment by Nuklear92** [comment]
Thank you, I'll give it a look! 👍
