### ISSUE TITLE
[Request]  Indicators

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/skin.eminence.2#86]
Would it be possible to have the watched indicators show on widget posters? I.e. progress, watched ect.  

P.S. it looks like you updated widget to be active seems much faster not having to reload all 👍

![image](https://user-images.githubusercontent.com/63697905/135746138-4738c949-fb94-4555-92d6-e6d14fca43ce.png)

**Comment by jurialmunkey** [comment]
Already exists.
`Skin Settings > Library > Unwatched episodes (numeric counter)`

![Honeyview_screenshot00066](https://user-images.githubusercontent.com/4618719/135792145-2610da24-a30a-4488-8428-738ff6b97a32.jpg)

**Comment by jurialmunkey** [comment]
Ah wait! I see you're specifically asking about widget posters not in the library. Re-opening.

**Comment by derrgoo** [comment]
Specifically asking for them to show on widget posters. Doesn't need to be as fancy as Arctic but showing progress episodes,watched.  

![image](https://user-images.githubusercontent.com/63697905/135793983-bf34a395-8eb2-4f3f-ae7f-0b009ffb45eb.png)

**Comment by derrgoo** [comment]
Maybe I didn't explain properly. The indicators are on list view but was wondering if you can add them to the widget poster as you have done in horizon?

**Comment by derrgoo** [comment]
My fault. Sorry I just downloaded recent from GitHub. Awesome thank you. 🙏
