### ISSUE TITLE
[Request]  Indicators

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/skin.eminence.2#87]
Would it be possible to have the watched indicators show on widget posters? I.e. progress, watched ect.  

P.S. it looks like you updated widget to be active seems much faster not having to reload all 👍

![image](https://user-images.githubusercontent.com/63697905/135746053-57acff02-ce4b-44fb-8336-86c2db783e72.png)

**Comment by jurialmunkey** [comment]
Duplicate of https://github.com/jurialmunkey/skin.eminence.2/issues/86

**Comment by jurialmunkey** [comment]
FYI - Already exists. See here: https://github.com/jurialmunkey/skin.eminence.2/issues/86#issuecomment-933127489
