### ISSUE TITLE
Chinese language support

### ISSUE THREAD

**Issue by mathflair** [jurialmunkey/skin.eminence.2#9]
I would love it if this skin could add support for the Chinese language.

**Comment by mathflair** [comment]
Any comment on this issue? Is this something you are unwilling to add support for?

The problem is that the fonts don't display Unicode Chinese.

**Comment by leoetlino** [comment]
Using Noto CJK or Source Han Sans (they're the same) will mess up the line-height, for some reason. To work around this issue, I'm using a custom font which is Roboto + DroidSansFallback which uses Roboto as base font, then DroidSansFallback as fallback for CJK characters.

You can use [this script](https://gist.github.com/leoetlino/418c5131a91305a6bb6d8f71f5a599dd) (I didn't write it, found it on the Kodi bug tracker and adapted it) to merge the fonts. It works fine for me.
