### ISSUE TITLE
[BUG] View: Media Info 2 for Seasons not showing check mark for completed seasons

### ISSUE THREAD

**Issue by Nuklear92** [jurialmunkey/skin.eminence.2#93]
When you select this Media view for viewing Seasons it's not showing any check marks ✅ if you had completed that Season like every other Media View does. I'll provide a clip below comparing other media views to Media Info 2, other ones are showing ✅ correctly.

![image](https://user-images.githubusercontent.com/76958541/136705897-084572af-b4cc-46aa-9773-af52f0d8fe6e.png)

https://user-images.githubusercontent.com/76958541/136706001-0f568c7f-808b-4309-a776-30a46e60cd08.MOV

**Comment by jurialmunkey** [comment]
I know why I put the indicators on the left for that view but I have no idea why I disabled them altogether for seasons/sets. Anyway, should be fixed now.
