### ISSUE TITLE
[BUG] Eminence not showing substitute FanArt Artwork for Episodes with missing thumbnail when using your own API Key

### ISSUE THREAD

**Issue by Nuklear92** [jurialmunkey/skin.eminence.2#95]
As the title says, Eminence isn't showing substitute FanArt for episodes with missing Artwork like Arctic Horizon does when you enter your personal FanArt API Key. Instead It shows the TMDb Backdrop of the show. I'll post comparison screenshots below between both skin. I even tried other Add-ons and the issue is the same regardless of having the key entered on each one.

### How Eminence shows:
![586B6DC7-993E-4712-941D-90498531849A_1_201_a](https://user-images.githubusercontent.com/76958541/137042428-1ef34a81-fbbd-4300-a0c9-fe5e37d3fa3e.jpeg)
![25D40CF2-922F-47DB-A159-AFBF5A7B713B_1_201_a](https://user-images.githubusercontent.com/76958541/137042429-f894a057-3455-4c91-8b3e-99940511d563.jpeg)

### How Arctic Horizon shows:
![4A78E8DC-05B2-4609-97FF-91DE5F36185C_1_201_a](https://user-images.githubusercontent.com/76958541/137042511-ceec97de-3e93-4706-a416-31078209a763.jpeg)
![079C976B-8F2A-4A4F-959D-27F6C3185929_1_201_a](https://user-images.githubusercontent.com/76958541/137042512-a4e81019-08f2-472b-bdb0-f255e4c750cd.jpeg)

### Personal FanArt Key entered
![09A1F02D-1D89-4E64-BB07-73DAD9A58AD8_1_201_a](https://user-images.githubusercontent.com/76958541/137042606-da2ecc97-90b9-491d-9f4b-62958f476dc8.jpeg)

**Comment by drinfernoo** [comment]
Eminence doesn't have the option to use `landscape` artwork, the way AH does.

**Comment by jurialmunkey** [comment]
Added in v4.1.8

Skin Settings > Library > Prefer landscape artwork over fanart
